version: 2.1

orbs:
  maven: circleci/maven@1.0.3


workflows:
  maven_test:
    jobs:
      - maven: # checkout, build, test, and upload test results
          command: "clean install -DskipTests"
          
