version: 1.0
jobs:
  say-hello:
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"


workflows:
  say-hello-workflow:
    jobs:
      - say-hello
